# This workflow updates the hash files and creates a release

name: Release Workflow
on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      overwrite:
        description: Create a new release without using data from the last one
        type: boolean
        required: true
        default: "false"
  push:
    branches:
      - main
    paths:
      - 'src/tech_list.json'

jobs:
  json-release:
    name: "JSON Hash Files Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Restore git repo cache
        if: ${{ github.event.inputs.overwrite != 'true' }}
        uses: actions/cache@v4
        with:
          path: .git-cache
          key: git-repos-${{ hashFiles('src/tech_list.json') }}
          restore-keys: |
            git-repos-

      - name: "Download previous JSON files"
        if: ${{ github.event.inputs.overwrite != 'true' }}
        uses: "robinraju/release-downloader@v1.11"
        continue-on-error: true
        with:
          repository: "Cyberwatch/HashThePlanet"
          latest: true
          fileName: "*_hash_files.json"
          tarBall: false
          zipBall: false
          out-file-path: "dist/"

      - name: "Generate JSON hash files"
        run: |
          hashtheplanet --input src/tech_list.json --json-dir dist/ --cache-dir .git-cache --workers 4

      - name: "Publish the release with the tag: ${{ steps.date.outputs.date }}"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}"
          prerelease: false
          title: "Hash files release: ${{ steps.date.outputs.date }}"
          files: |
            dist/*_hash_files.json

      - name: "Publish the release with the tag: latest"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Hash files release: Latest"
          files: |
            dist/*_hash_files.json
